name: module3_task0
on:
push:
schedule:
      - cron: '0  15  * * *'
jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: running make help
      run: make help -C module3_task0
